// DAW Client/React/TiendaGuitarra/src/components/Guitarra.jsx
export default function Guitarra({ guitarraObj, anyadirAlCarrito }) {
  console.log(guitarraObj);
  const { id, name, description, price, image } = guitarraObj;


  return (
    <>
      <div className="col-md-6 col-lg-4 my-4 row align-items-center">
        <div className="col-4">
          <img
            className="img-fluid"
            src={`./public/img/${image}.jpg`}
            alt="imagen guitarra"
          />
        </div>
        <div className="col-8">
          <h3 className="text-black fs-4 fw-bold text-uppercase">{name}</h3>
          <p>{description}</p>
          <p className="fw-black text-primary fs-3">{price}€</p>
          <button
            type="button"
            className="btn btn-dark w-100"
            onClick={() => anyadirAlCarrito(guitarraObj)}
          >
            Agregar al Carrito
          </button>
        </div>
      </div>
    </>
  );
}

// DAW Client/Vue/TiendaGuitarra/src/components/Guitarra.vue
<script setup>

const props = defineProps({
    guitarra: {
        type: Object,
        required: true
    }
})

</script>

<template>
  <div class="col-md-6 col-lg-4 my-4 row align-items-center">
    <div class="col-4">
      <img class="img-fluid" src="/img/guitarra_01.jpg" alt="imagen guitarra" />
    </div>
    <div class="col-8">
      <h3 class="text-black fs-4 fw-bold text-uppercase">
        {{guitarra.nombre}}
      </h3>
      <p>
        {{guitarra.descripcion}}
      </p>
      <p class="fw-black text-primary fs-3">{{guitarra.precio}}€</p>
      <button type="button" class="btn btn-dark w-100">
        Agregar al Carrito
      </button>
    </div>
  </div>
</template>

<style lang="scss" scoped></style>
